name: 'Deploy to Payara Cloud'
description: 'Deploy ClusterJSP to Cloud on update of master'

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - 'README.adoc'
      - '**/README.adoc'
      - 'public/**'
      - 'static/**'
      - 'tests/**'
      -

jobs:
  deploy:
    runs-on: ubuntu-latest
  steps:
    - name: Deploy to Payara Cloud
      uses: payara/cloud-deploy@master
      with:
        token: ${{ secrets.PCL_AUTH_TOKEN }}
        subscription_name: 'rohan 2025-01-30'
        namespace: 'start-dev'
        app_name: 'your-app'
        artifact_location: '../../../clusterJSP/target/clusterjsp-1-SNAPSHOT.war'
        deploy: true