name: 'Deploy to Payara Cloud'
description: 'Deploy ClusterJSP to Cloud on update of master'

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '.github/**'
      - 'README.adoc'
      - '**/README.adoc'
      - 'public/**'
      - 'static/**'
      - 'tests/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

  env:
    ACTIONS_STEP_DEBUG: true
    PCL_ENDPOINT: ${{ secrets.PCL_ENDPOINT }}
    PCL_CLIENT_ID: ${{ secrets.PCL_CLIENT_ID }}

    steps:
      - name: Deploy to Payara Cloud
        uses: payara/cloud-deploy@master
        with:
          token: ${{ secrets.PCL_AUTH_TOKEN }}
          subscription_name: 'your-subscription-name'
          namespace: 'your-namespace'
          app_name: 'your-app'
          artifact_location: 'your-artifact.war'
          deploy: true