name: 'Deploy to Payara Cloud'
description: 'Deploy ClusterJSP to Cloud on update of master'

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
      PCL_ENDPOINT: ${{ secrets.PCL_ENDPOINT }}
      PCL_CLIENT_ID: ${{ secrets.PCL_CLIENT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
      - name: Build with Maven
        run: mvn clean package
        working-directory: ./clusterJSP
      - name: Deploy to Payara Cloud
        uses: payara/cloud-deploy@master
        with:
          token: ${{ secrets.PCL_AUTH_TOKEN }}
          subscription_name: 'rohan 2025-01-30'
          namespace: 'start-dev'
          app_name: 'your-app'
          artifact_location: './clusterJSP/target/clusterjsp-1-SNAPSHOT.war'
          deploy: true